### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by jumining** [29th-WE-SOPT-iOS-Part/ImJuMin#7]
## 📌  Feature Issue

로그인 회원가입에 실제 API를 붙여보는 과제

## 📝  To-do

- [ ] 시작화면에서 로그인화면으로의 전환
- [ ] 로그인 화면에서 다음 버튼 누르면 서버 통신하고 alert 띄우기
- [ ] 회원가입 화면에서 다음 버튼 누르면 서버 통신하고 alert 띄우기
